spring:
  application:
    name: bankcard

  profiles:
    active: dev

  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20

  autoconfigure:
    exclude:  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

server:
  port: 8080
