spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/bankcards
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/migration/db.changelog-master.yaml

app:
  jwt:
    secret-key: Lwn+2LbsHYTgi5DEiF5sYRKvXGWQ3zA5oS6WNeHTOaQ=
    expiration: 86400
  admin:
    email: admin@gmail.com
    password: password123
  encryption:
    key: GJBoohQoSMBorPlhbb2TRBIbnyHQStH5VGzWW2P66kc=
    salt: 4fe802cd2d3bab64

springdoc:
  swagger-ui:
    display-request-duration: true
    try-it-out-enabled: true
    enabled: true
  api-docs:
    enabled: true
    path: /v3/api-docs